name: CommandAPI .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [master]

env:
  bldConfig: Release
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration $bldConfig --no-restore
      working-directory: ./src/CommandAPI
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: ./test/CommandAPI.Tests
